version: '3.7'

services:

  server:
    build: ./
    restart: always
    ports:
      - 80:8080
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres
      - PORT=8080
      - DBFLAG=false
  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
